### ISSUE TITLE
Need mask prompt

### ISSUE THREAD

**Issue by jsrdcht** [mazurowski-lab/finetune-SAM#22]
Hello, may I ask would you have the plan that if mask can be used as a prompt input?

**Comment by haoyudong-97** [comment]
Hi, we don't have the plan for that now since our primary focus is on automatic segmentation, i.e., segmentation without prompts. 

But you could modify our code at https://github.com/mazurowski-lab/finetune-SAM/blob/607854de056f7deb87632b8de7ad47ada6e43635/SingleGPU_train_finetune_noprompt.py#L104
where you can replace None with the mask prompt
